// Autogenerated code by vite-plugin-svg-sprite-names-typescript
export type IconName = "settings" | "study" | "eye" | "back" | "play" | "paused";
export const IconNameList = ["settings", "study", "eye", "back", "play", "paused"] as const;
